# Generated by Django 4.2.3 on 2024-03-27 09:47

import arm.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployed',
            name='date_of_deploy',
            field=models.DateField(default=datetime.date(2024, 3, 27)),
        ),
        migrations.AlterField(
            model_name='deployed',
            name='project_start_date',
            field=models.DateField(default=datetime.date(2024, 3, 27), verbose_name=' Enter project start date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateField(default=datetime.date(2024, 3, 27)),
        ),
        migrations.AlterField(
            model_name='onbordstable',
            name='alt_mobile_no',
            field=models.IntegerField(default=0, validators=[arm.models.phon_num]),
        ),
        migrations.AlterField(
            model_name='onbordstable',
            name='graduation',
            field=models.CharField(choices=[('Bsc', 'Bsc'), ('Btech', 'Btech'), ('AgBSc', 'AgBSc'), ('BBA', 'BBA'), ('Bcom', 'Bcom'), ('BE', 'BE'), ('BCA', 'BCA')], max_length=300),
        ),
        migrations.AlterField(
            model_name='onbordstable',
            name='graduation_stream',
            field=models.CharField(choices=[('computer science', 'computer science'), ('mathematics', 'mathematics'), ('science', 'science'), ('data science', 'data science'), ('computer applications', 'computer applications')], max_length=250),
        ),
        migrations.AlterField(
            model_name='onbordstable',
            name='mobile_no',
            field=models.IntegerField(validators=[arm.models.phon_num]),
        ),
        migrations.AlterField(
            model_name='onbordstable',
            name='pg_education',
            field=models.CharField(choices=[('Msc', 'Msc'), ('MBA', 'MBA'), ('Mtech', 'Mtech'), ('ME', 'ME'), ('MCA', 'MCA')], max_length=250),
        ),
        migrations.AlterField(
            model_name='onbordstable',
            name='pg_stream',
            field=models.CharField(choices=[('computer science', 'computer science'), ('mathematics', 'mathematics'), ('science', 'science'), ('data science', 'data science'), ('computer applications', 'computer applications'), ('civil engineering', 'civil engineering'), ('Finance', 'Finance'), ('IT', 'IT')], max_length=250),
        ),
        migrations.CreateModel(
            name='Exit_raise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_raise', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='arm.employee')),
            ],
        ),
    ]
