# Generated by Django 4.2.3 on 2024-03-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0002_alter_deployed_date_of_deploy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_propertise',
            name='Adapter_description',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='company_propertise',
            name='Laptop_description',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='company_propertise',
            name='Mouse_description',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='company_propertise',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='arm.employee'),
        ),
    ]
