# Generated by Django 4.2.3 on 2024-03-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0003_company_propertise_adapter_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_propertise',
            name='Adapter',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='company_propertise',
            name='Bag',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='company_propertise',
            name='Mouse',
            field=models.BooleanField(),
        ),
    ]
