# Generated by Django 4.2.3 on 2024-04-15 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0004_alter_company_propertise_adapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployed',
            name='date_of_deploy',
            field=models.DateField(default=datetime.date(2024, 4, 15)),
        ),
        migrations.AlterField(
            model_name='deployed',
            name='project_start_date',
            field=models.DateField(default=datetime.date(2024, 4, 15), verbose_name=' Enter project start date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateField(default=datetime.date(2024, 4, 15)),
        ),
    ]
